server:
  port: 8082
  servlet:
    context-path: /

#配置数据库连接相关信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlyk
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 18000000
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 5000
      idle-timeout: 0
#  ai:
#    openai:
#      api-key: ${AI_DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1  # 如果 DeepSeek 的 embedding API 是这个路径
#      chat:
#        options:
#          model: qwen-max
#      embedding:
#        options:
#          model: text-embedding-v2 # ⚠️ 注意：这里的模型名称要和 DeepSeek 支持的一致！
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v2  # ✅ 注意：你确认这个模型确实存在
    openai:
      api-key: ${AI_DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.chat.client.ChatClientAutoConfiguration


  #配置redis的连接信息
  #redis
  data:
    redis:
      database: 10
      host: localhost
      password:
      port: 6379

  #设置jackson返回json数据时，时区和格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#指定一下mapper.xml文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #在控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#定义定时任务的调度时间
project:
  task:
    cron: '0 0/5 * * * ?'
#    delay: 180000